spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/duchetty/ConfigServer.git
          clone-on-start: true
server:
  port: 9094
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true